export const data = {
  pageProps: {
    user: {
      id: 0,
      loginId: null,
      nickName: null,
      doctorId: 0,
      sex: null,
      profileImage: null,
      level: 0,
      birthYear: 0,
      country: null,
      myHospitalDistrict: {},
      districts: [],
      phoneNational: null,
      agreeEmail: false,
      agreeMarketing: false,
      agreeSms: false,
      sendPushAd: false,
    },
    authorization: "e67b64ecc5514f0c9e410ba970214b00",
    keyword: "안면윤곽/양악",
    treatmentCategoryName: "안면윤곽/양악",
    treatmentCategoryId: 414,
    breadcrumb: [
      {
        text: "홈",
        href: "/",
      },
      {
        text: "안면윤곽/양악",
        href: "/search?category=안면윤곽/양악",
      },
    ],
    totalLength: 11711,
    eventTotalLength: 621,
    communityDocumentTotalLength: 987,
    hospitalTotalLength: 103,
    treatmentTotalLength: 0,
    reviewTotalLength: 10000,
    reviews: [],
    events: [
      {
        id: 10032,
        title: "리스펙 안면윤곽 ",
        titleImage:
          "https://image2.gnsister.com/images/direct/1715574746964_5455ac7fb4e146c1ac5beb2e9a956d88.jpg?originalImageWidth=1080&originalImageHeight=1080",
        treatmentList: [
          "광대축소(앞광대)",
          "사각턱수술",
          "턱끝축소",
          "턱끝수술",
          "광대축소(옆광대)",
          "안면윤곽재수술",
          "광대축소(전체)",
        ],
        hospitalId: 2221,
        hospitalSubwayCode: "SUB_S2_222,SUB_S9_925",
        hospitalSubway: "강남역",
        hospitalName: "리스펙성형외과",
        discountedCost: 2750000,
        cost: 2750000,
        currency: "KRW",
        discountRate: 0,
        rating: 9.8,
        ratingCount: 670,
        type: "EVENT",
        vat: "INCLUDED",
        createTime: 1572573213000,
        assessmentState: "GROWTH",
        useBuyNow: false,
      },
      {
        id: 15632,
        title: "안면윤곽",
        titleImage:
          "https://image2.gnsister.com/images/direct/1705979731516_7567aa23a4904df1997121cd7b4d57f5.jpg?originalImageWidth=1080&originalImageHeight=1080",
        treatmentList: [
          "사각턱수술",
          "턱끝수술",
          "안면윤곽재수술",
          "V라인축소술",
          "양악수술",
        ],
        hospitalId: 289,
        hospitalSubwayCode: "SUB_S3_337,SUB_S7_732",
        hospitalSubway: "신사역",
        hospitalName: "이유구강악안면외과치과의원",
        discountedCost: 3190000,
        cost: 6300000,
        currency: "KRW",
        discountRate: 49,
        rating: 9.6,
        ratingCount: 14,
        type: "EVENT",
        vat: "INCLUDED",
        createTime: 1606435090000,
        assessmentState: "CERTIFIED",
        useBuyNow: false,
      },
      {
        id: 11467,
        title: "나나_안면윤곽",
        titleImage:
          "https://image2.gnsister.com/images/direct/1710750856361_78c955b48f424b0d9045614879979ac9.jpg?originalImageWidth=1080&originalImageHeight=1080",
        treatmentList: [
          "광대축소(앞광대)",
          "사각턱수술",
          "턱끝축소",
          "광대축소(옆광대)",
          "광대축소(전체)",
        ],
        hospitalId: 938,
        hospitalSubwayCode: "SUB_S9_925,SUB_S7_732",
        hospitalSubway: "신논현역",
        hospitalName: "나나성형외과의원",
        discountedCost: 4939000,
        cost: 4939000,
        currency: "KRW",
        discountRate: 0,
        rating: 9.7,
        ratingCount: 237,
        type: "EVENT",
        vat: "INCLUDED",
        createTime: 1581875065000,
        assessmentState: "GROWTH",
        useBuyNow: false,
      },
      {
        id: 13272,
        title: "뷰_안면윤곽",
        titleImage:
          "https://image2.gnsister.com/images/direct/1710225145229_654bde7d3eff42e08be185922b469891.jpg?originalImageWidth=1080&originalImageHeight=1080",
        treatmentList: [
          "광대축소(앞광대)",
          "사각턱수술",
          "턱끝축소",
          "광대축소(전체)",
        ],
        hospitalId: 189,
        hospitalSubwayCode: "SUB_S9_925,SUB_S2_222",
        hospitalSubway: "신논현역",
        hospitalName: "뷰성형외과",
        discountedCost: 2750000,
        cost: 2750000,
        currency: "KRW",
        discountRate: 0,
        rating: 9.6,
        ratingCount: 60,
        type: "EVENT",
        vat: "INCLUDED",
        createTime: 1594076467000,
        assessmentState: "CERTIFIED",
        useBuyNow: false,
      },
      {
        id: 13358,
        title: "안면윤곽은 역시 그랜드",
        titleImage:
          "https://image2.gnsister.com/images/direct/1714624976437_e68a7b41f499412cb58c5d393d9ec358.jpg?originalImageWidth=1080&originalImageHeight=1080",
        treatmentList: [
          "광대축소(앞광대)",
          "사각턱수술",
          "턱끝수술",
          "광대축소(옆광대)",
          "광대축소(전체)",
        ],
        hospitalId: 62,
        hospitalSubwayCode: "SUB_S3_336",
        hospitalSubway: "압구정역",
        hospitalName: "그랜드성형외과",
        discountedCost: 2199000,
        cost: 4290000,
        currency: "KRW",
        discountRate: 49,
        rating: 9.9,
        ratingCount: 186,
        type: "EVENT",
        vat: "INCLUDED",
        createTime: 1594671242000,
        assessmentState: "CERTIFIED",
        useBuyNow: false,
      },
      {
        id: 22266,
        title: "윤곽3종 퍼펙트 안면윤곽 성형은 아이디",
        titleImage:
          "https://image2.gnsister.com/images/direct/1712713000352_dd1a5bfd295b40f3af4cbbe450a353ec.jpg?originalImageWidth=1080&originalImageHeight=1080",
        treatmentList: [
          "광대축소(앞광대)",
          "사각턱수술",
          "턱끝축소",
          "턱끝수술",
          "광대축소(옆광대)",
          "V라인축소술",
          "광대축소(전체)",
          "퀵광대",
        ],
        hospitalId: 257,
        hospitalSubwayCode: "SUB_S3_337,SUB_S7_731,SUB_S7_732,SUB_S3_336",
        hospitalSubway: "신사역",
        hospitalName: "아이디병원-본원",
        discountedCost: 5489000,
        cost: 5489000,
        currency: "KRW",
        discountRate: 0,
        rating: 9.9,
        ratingCount: 494,
        type: "EVENT",
        vat: "INCLUDED",
        createTime: 1628031996000,
        assessmentState: "CERTIFIED",
        useBuyNow: false,
      },
    ],
    communityDocuments: [
      {
        id: 2716346,
        categoryId: 2,
        categoryName: "시술/수술 전 질문",
        writer: {
          id: 4400900,
          doctorId: 1041,
          profile:
            "https://image2.gnsister.com/images/member/profile/1688020614626_26054245ecc145fab4c05e20f20f601a.jpg?originalImageWidth=960&originalImageHeight=1440",
          nickname: "최우경",
          level: 7,
          engagementType: null,
        },
        writerDoctorId: 1041,
        hasThumbUp: false,
        commentCount: 1,
        thumbUpCount: 0,
        viewCount: 8,
        createTime: "약 22시간 전",
        edited: true,
        title: "",
        contents:
          "Q. 안면 윤곽주사를 통한 얼굴 윤곽 라인 관리 가능할까?\r\n\r\nA. 안면윤곽 주사란 안면윤곽 주사처럼 광범위한 부위에 대한 전체적인 교정을 진행하는 것이 아닌\r\n특정 부위의 지방세포를 분해하여 얼굴의 윤곽을 개선하는 시술입니다.\r\n해당 안면 윤곽주사는 주로 볼이나 턱 아래 이중턱이 자주 발생하는 턱 밑 지방 라인에 시술을 진행하여 지방을 감소시키는 용도로 많으 사용이 되고 있습니다.\r\n\r\n​수술이 아닌 비침습적 방법으로 얼굴의 라인을 더욱 선명하게 만들고자 할 때 시행됩니다.\r\n안면 윤곽주사는 주로 인산염, 탈수소나트륨, 콜라겐아제와 같은 지방 분해 효소, 또는 히알루로니다제 등이 포함되어 있습니다.\r\n\r\n​해당 성분들은 지방세포를 분해하거나, 지방의 배출을 촉진시켜 얼굴의 슬리밍 효과를 줄 수 있습니다.\r\n안면 윤곽주사는 대체로 주사로 지방 세포를 파괴하면서 지속적으로 시술을 하는 경우 효과는 영구적일 수 있습니다.\n\r\n하지만, 시술 받으신 환자의 생활 습관, 체중 변화, 노화 과정 등에 따라 효과의 지속성이 달라질 수 있습니다.\r\n그리하여, 안면 윤곽주사 시술을 받으셨다고 하셔도 주기적인 관리를 통해서 얼굴 윤곽 라인 관리를\r\n진행해주시는 것을 추천드립니다.\r\n\r\n#안면윤곽 #윤곽수술 #양악 #양악수술 #V라인 #턱선 #사각턱 #광대 #턱끝 #긴곡선 #더긴곡선 #사각턱축소술 #광대축소술 #턱끝전진 #턱끝후퇴 #윤곽 #강남 #강남성형외과 #비유 #비유성형외과",
        photos: [
          {
            url: "https://image2.gnsister.com/images/document/1716867120809_ba4aafb19c0e43e58a845d76bf8dc679.jpg?originalImageWidth=773&originalImageHeight=773",
          },
          {
            url: "https://image2.gnsister.com/images/document/1716867120855_b2dd957b144c420690f8a9b606c4c8a4.jpg?originalImageWidth=773&originalImageHeight=773",
          },
          {
            url: "https://image2.gnsister.com/images/document/1716867120852_2e0610d31a8f44ba99c7c4a6352eb5f7.jpg?originalImageWidth=773&originalImageHeight=773",
          },
        ],
        lang: "ko",
        hasDoctorComment: false,
        translateResult: null,
      },
      {
        id: 2562231,
        categoryId: 11,
        categoryName: "병원질문",
        writer: {
          id: 3146837,
          doctorId: null,
          profile:
            "https://image2.gnsister.com/images/member/profile/1513135488959_4131ffc481d74b849460ec1ea11fd9d5.png",
          nickname: "쑤우요",
          level: 4,
          engagementType: "OPERATED",
        },
        writerDoctorId: null,
        hasThumbUp: false,
        commentCount: 29,
        thumbUpCount: 1,
        viewCount: 575,
        createTime: "2024.02.25",
        edited: true,
        title: "",
        contents:
          "윤곽 병원 추렸는데 고수 언니들 함 봐줘요!\n(자려한 느낌 조아해요 너무 화려나 너무 자연은 싫고!)\n\n- 소다\n- 비티\n- 본디 \n- 1퍼센트 \n-쿠키\n- 리스펙 \n- 휴먼\n#안면윤곽/양악 #화려 #2종 #3종 #턱 #광대 #윤곽톡스 #발품",
        photos: [
          {
            url: "https://image2.gnsister.com/images/document/1708867848798_967455bce7f04d9e9695cda4386e7888.jpg?originalImageWidth=898&originalImageHeight=1275",
          },
        ],
        lang: "ko",
        hasDoctorComment: false,
        translateResult: null,
      },
      {
        id: 2424841,
        categoryId: 2,
        categoryName: "시술/수술 전 질문",
        writer: {
          id: 1297242,
          doctorId: 1208,
          profile:
            "https://image2.gnsister.com/images/member/profile/1617954124630_0cc6cbf8ea8e4687962f7bfbfc210dcd.jpg?originalImageWidth=800&originalImageHeight=800",
          nickname: "강병수",
          level: 4,
          engagementType: null,
        },
        writerDoctorId: 1208,
        hasThumbUp: false,
        commentCount: 12,
        thumbUpCount: 275,
        viewCount: 686,
        createTime: "2023.12.10",
        edited: true,
        title: "",
        contents:
          "Q.나이가 어린데 얼굴이 왜이렇게 처질까요?젊은데 거상술 해야할까요?\r\n\r\n#미니거상술#안면거상술#거상연령#처지는이유#안면처짐#우리성형외과#우리#ㅇㄹ#선릉\r\n\r\nA.안녕하세요🖐️\r\n\r\n우리성형외과 주름성형을 담당하고 있는👨‍⚕️강병수원장입니다.\r\n\r\n오늘은 최근들어 얼굴이 처지는 원인과 거상을 받는 연령대에대해 궁금해 하는 분들이 많아\r\n\r\n얼굴 처짐이 발생, 가속화되는 이유에 대해 알려드리려고 합니다.\r\n\r\n보통은 젊으신 분들이 찾아오시는경우는 크게 세가지입니다.\r\n\r\n1️⃣첫번째로는 양악과 안면윤곽수술 후 발생되는 처짐입니다.\r\n\r\n사각턱수술, 광대수술등을 30대 이후에 하게되는경우 처짐이 발생할 가능성이 높아집니다.\r\n\r\n비슷한 이유로 발치 교정을 하시는 분들도 처짐이 동반되는경우가 종종 발생하여 수술을 받으시는 분들이 많습니다.\r\n\r\n\r\n2️⃣두번째로 과도하게 단기간, 짧은시간내 다이어트를 하시는 분들이 처짐이 발생하는경우가 많습니다.\r\n\r\n덧붙여 노산이시거나, 단식원에서 체중을 감량하시는분들 (10kg~이상)이 처짐이 발생할 확률이 높습니다.\r\n\r\n\r\n3️⃣마지막으로 얼굴에 지방이식이나 이물질, 필러같은걸 넣어서 볼이 좀 무거운 경우인데 이런 것들이 얼굴에 있는경우 처짐이 가속화됩니다.\r\n\r\n연령대가 낮으나 상대적으로 빠르게 얼굴이 처지게되는 원인에 대해 설명해드렸습니다.\r\n\r\n\r\n한동안 동안 열풍이 불면서 노화를 막기위해 부단한 노력들을 많이 하십니다.\r\n\r\n허나 나이에 비해서 얼굴이 좀 더 처져서 레이저리프팅, 실리프팅으로도 해결 하지 못해 거상을 고려하시는 분들이 많으신데요.\r\n\r\n젊은이 늙은이는 상대적인것이라 본인이 젊은지 늙었는지가 중요한것이 아니라 \r\n \r\n동년배들에 비해 나이가 들어보이는 것이 가장 큰 문제 입니다. \r\n\r\n거상은 노안인분들이 보통 고려하십니다.\r\n\r\n즉, 상대적 나이가 중요한 수술입니다.\r\n\r\n상대적인 노안으로 인한 스트레스가 상단한 분들이 주로 수술하십니다.\r\n\r\n고정관념으로 인해 수술을 망설이시는 분들은 노화개선만 늦출뿐입니다.\r\n\r\n얼굴 처짐의 원인들에 대한 궁금증이 어느정도 해소 되셨는지 궁금하네요😊\r\n\r\n궁금하신 점이 있으시다면 댓글로 남겨주세요. 성실히 답변드리도록 하겠습니다.\r\n\r\n감사합니다.",
        photos: [
          {
            url: "https://image2.gnsister.com/images/document/1702136269533_9cf9a686a7504f3dbee4b32e53490f10.jpg?originalImageWidth=832&originalImageHeight=830",
          },
          {
            url: "https://image2.gnsister.com/images/document/1702136269550_86b7949b1b5a409dbe06e0ec1afc85d9.jpg?originalImageWidth=900&originalImageHeight=900",
          },
          {
            url: "https://image2.gnsister.com/images/document/1702136269552_b15a3050278a4a7e90e3839f9df20ba6.jpg?originalImageWidth=900&originalImageHeight=900",
          },
        ],
        lang: "ko",
        hasDoctorComment: false,
        translateResult: null,
      },
    ],
    hospitals: [
      {
        id: 370,
        name: "팝성형외과의원",
        mainImage:
          "https://image2.gnsister.com/images/direct/1678167128052_6e4daae119b846e98ac9da648f98e5b9.jpg?originalImageWidth=600&originalImageHeight=240",
        rating: 9.4,
        ratingCount: 9974,
        reviewCount: 41042,
        supportingLangList: ["ja"],
        isCertified: false,
        assessmentState: "GROWTH",
        photos: [],
        sido: "서울",
        pageCount: 25,
      },
      {
        id: 938,
        name: "나나성형외과의원",
        mainImage:
          "https://image2.gnsister.com/images/direct/1677820120807_7329b9dcdc5746de8c5e01b9dbcc97bb.jpg?originalImageWidth=600&originalImageHeight=240",
        rating: 9.6,
        ratingCount: 15017,
        reviewCount: 39300,
        supportingLangList: ["ja"],
        isCertified: false,
        assessmentState: "GROWTH",
        photos: [],
        sido: "서울",
        pageCount: 72,
      },
      {
        id: 250,
        name: "디에이성형외과의원",
        mainImage:
          "https://image2.gnsister.com/images/hospital/1515034360262_edcd481595034a08a0190a2c3cf7a517.jpg",
        rating: 9.4,
        ratingCount: 8788,
        reviewCount: 32431,
        supportingLangList: ["ja"],
        isCertified: false,
        assessmentState: "GROWTH",
        photos: [],
        sido: "서울",
        pageCount: 81,
      },
    ],
    treatments: [],
    language: "ko-KR",
    token: "e67b64ecc5514f0c9e410ba970214b00",
    blogs: null,
    blogTotalLength: null,
    title: "'안면윤곽/양악'에 대한 검색결과 11711개 | 강남언니",
    meta: {
      description:
        "국내 1위 성형정보앱 강남언니. 리얼후기부터 가격비교, 상담예약까지 한번에. 강남언니를 지금 만나보세요.",
      image: "https://www.gangnamunni.com/images/kr/meta_thumb_02.jpg",
      locale: "ko_KR",
      name: "강남언니",
      title: "'안면윤곽/양악'에 대한 검색결과 11711개 | 강남언니",
      twtCardType: "summary_large_image",
      type: "website",
      desc: "'안면윤곽/양악'을 전문으로 하는 병원과 이벤트를 확인해보세요!",
    },
  },
  __N_SSP: true,
};
