export const data = {
  code: 0,
  result: {
    standardAdList: [],
    liteAdList: [
      {
        _id: "5c85f89d2fe3d80018150c88",
        gymName: "옥련 머슬몽키짐",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1696b532796862c8e/2Y8vkz32mNx7A2bto9kf7PHyzvzXCaFAhzpw.Big_74203666.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1696b532796862c8e/2YVrLMEgH47c44Ka48TRArNzyKSEWzpmf1V9.Small_74203666.jpg",
        address: "인천 연수구 옥련동",
        location: [126.650718, 37.422936],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "️무료 O.T 오리엔테이션",
        },
        service: {
          free: "️주차 / ️인바디 측정 / ️수건",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 239000,
          originalPrice: 264000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 10,
        },
        review: {
          rate: 4.15,
          count: 14,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
    ],
    centerList: [
      {
        _id: "64d9f05d6f0347001d1764db",
        gymName: "옥련 점핑앤온힐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/189f352ec10179e606/2YUdxPauVsnMx63Bx31kPXY3o2LZpYYmoRZt.list_photo.jpg",
        address: "인천 연수구 옥련동",
        location: [126.6508541, 37.4230444],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["점핑운동"],
        program: {
          free: "",
        },
        service: {
          free: "운동복 / 수건 / 주차",
        },
        price: {
          name: "점핑 피트니스",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1200000,
          originalPrice: 1200000,
          period: 12,
          priceType: "period",
          itemTags: ["점핑운동"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "64e5776f6f0347001d1bd051",
        gymName: "학익 팀에이치짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18a205a8b732daf317/2aGNgvGdVmFkm2q8bA5fJgSL5kmXREEZAksG.Small_230830_학익_팀에이치짐_02.jpg",
        address: "인천 미추홀구 학익동",
        location: [126.6569612, 37.4402766],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "수건 / 주차",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 320000,
          originalPrice: 320000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.5,
          count: 2,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "60d06128c70b9e0039960bfe",
        gymName: "옥련 더블유짐 ",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17a2dfb851ce072a6/kXaPzWvCgafTNn4Upqqrnkrmubf9A4uvZnmM844gat.jpg",
        address: "인천 연수구 옥련동",
        location: [126.64942239755673, 37.422400417573],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "O.T",
        },
        service: {
          free: "운동복 / 수건 / 락커 / Wi-fi / 주차",
        },
        price: {
          name: "헬스 + 운동복 + 락커",
          count: null,
          isLowestPrice: true,
          lowestPrice: 360000,
          originalPrice: 400000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 20,
        },
        review: {
          rate: 5,
          count: 3,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "60d03a42c70b9e003996080c",
        gymName: "옥련 티와이휘트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17a2d63923ebba1a3/kXaPzWtj7EhR3eMjaJL3ZB8MwVQP1H9YAQZWJqDzLa.jpg",
        address: "인천 연수구 옥련동",
        location: [126.644643, 37.423265],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "O.T 프로그램 (센터 별도 문의)",
        },
        service: {
          free: "운동복 / 수건 / 라커 / 주차 / 반신욕기 / 안마의자 / WI-FI",
        },
        price: {
          name: "헬스+운동복+라커",
          count: null,
          isLowestPrice: false,
          lowestPrice: 600000,
          originalPrice: 600000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 3,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "630c32c929f6ae001d0932ad",
        gymName: "학익 본어게인",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/182e7a661664406dd8/2Zvjxbr58owkyZu5inX6mKH9tRfXSQufu8us.센터 Small 복사.jpg",
        address: "인천 미추홀구 학익동",
        location: [126.66869630395904, 37.44165139396522],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["P.T", "그룹P.T"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        price: {
          name: "1:1 P.T",
          count: 30,
          isLowestPrice: false,
          lowestPrice: 1980000,
          originalPrice: 1980000,
          period: null,
          priceType: "count",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "623c414505aa82001d49b9ee",
        gymName: "인하대 피트니스연구소",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17fbb5ef6a56de548/kXadeiuwtBzb3rghEYNd4MEC7vfapxS4RcAVb7Kegx.jpg",
        address: "인천 미추홀구 용현동",
        location: [126.64954416904055, 37.44824962136421],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "지하주차장 3시간 주차",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 537000,
          originalPrice: 537000,
          period: 12,
          priceType: "period",
          itemTags: [],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 4,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6114dabeec7d1e0039f542d9",
        gymName: "연수 클래식컬짐PT",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17b397678da357dcc3/4K7xc97BgaQnksTiwPBQ2AyJWx3qwA66BzT6phsdEiBa.jpg",
        address: "인천 연수구 청학동",
        location: [126.67614955322371, 37.41786413902608],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "수건",
        },
        price: {
          name: "PT + 회원권",
          count: 50,
          isLowestPrice: false,
          lowestPrice: 2500000,
          originalPrice: 2500000,
          period: null,
          priceType: "count",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 1,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "65321cdd8d5c02001d40d37d",
        gymName: "용현 무무짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18b4bc0c30a3846b83/2aGTRseisqfyqhDVCvFLByvXRSXcyESAsyFR.센터 Small 복사.jpg",
        address: "인천 미추홀구 용현동",
        location: [126.6336933525677, 37.44993424368173],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "동적평가 체형측정 1회 무료",
        },
        service: {
          free: "주차 : 건물 지하1층 & 지상 1층 주차장 보유",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 528000,
          originalPrice: 528000,
          period: 12,
          priceType: "period",
          itemTags: [],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 1,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6486ddff3fcd1a001d891b4f",
        gymName: "주안 아이앤지필라테스&플라잉",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/188aed32deb4e58ca0/2aFaej3aCB8sWaxrVDfi7GaBUiov3EtjVFvS.센터 Small 복사.jpg",
        address: "인천 미추홀구 주안동",
        location: [126.67898676806276, 37.44852747236405],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["기구필라테스", "플라잉요가"],
        program: {
          free: "",
        },
        service: {
          free: "주차 시간제한 없음",
        },
        price: {
          name: "1:1개인레슨",
          count: 50,
          isLowestPrice: false,
          lowestPrice: 2750000,
          originalPrice: 2750000,
          period: null,
          priceType: "count",
          itemTags: ["필라테스", "기구필라테스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "602b898fe0fd8e0039c7950c",
        gymName: "용현 그레이짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/177aa1156f6dd2e5b/kXYVtVafvFurXYyMGPyhRVEKo8XPEU2ZXi2JuVDoyi.jpg",
        address: "인천 미추홀구 용현동",
        location: [126.63274678257133, 37.45277066552486],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️수건 / WI-FI / 주차",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 420000,
          originalPrice: 420000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 3,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "5a7a6d2b01bd9f037173c8ef",
        gymName: "연수 CJ휘트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1616e3a730b4e8219c/Small)CJ.jpg",
        address: "인천 연수구 동춘동",
        location: [126.671491, 37.407326],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "O.T 1회",
        },
        service: {
          free: "주차 2시간",
        },
        price: {
          name: "P.T (주 2회)",
          count: 48,
          isLowestPrice: false,
          lowestPrice: 1400000,
          originalPrice: 1400000,
          period: null,
          priceType: "count",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 2.88,
          count: 1,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "621f18b943554f0039fd73bc",
        gymName: "연수 고잉짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17f497894d91e3879e/4K7yQfxdGEWd89FSpKZxuT8Nu1XCvY7PGUk1VmNyfN3z.jpg",
        address: "인천 연수구 동춘동",
        location: [126.67102975184703, 37.40679768822917],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "그룹P.T"],
        program: {
          free: "체형분석과 인바디 상담",
        },
        service: {
          free: "",
        },
        price: {
          name: "PT 이용권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1485000,
          originalPrice: 1485000,
          period: 6,
          priceType: "period",
          itemTags: [],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "66135bb95e60cd001d02c099",
        gymName: "동춘 플라이휘트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18ebb9e4bdf1d38b96/2aGrVccJKRuBSPSG9PKKzAhHyqiFi2pMLonu.list_photo.jpg",
        address: "인천 연수구 동춘동",
        location: [126.67255178877048, 37.40743487733875],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️수건",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 396000,
          originalPrice: 396000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "623d79bd05aa82001d4a0403",
        gymName: "용마루 피트니스연구소",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17fc0238dfa4e27bc7/4K7ySocsnR2xNBFMNAkiVtUZ7jMjkMVftx8zbrK3tr8Y.jpg",
        address: "인천 미추홀구 용현동",
        location: [126.64481396559593, 37.459097846663326],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "그룹P.T"],
        program: {
          free: "",
        },
        service: {
          free: "지하 주차장",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 512000,
          originalPrice: 512000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4,
          count: 1,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "62f5c8801df81f001dd645fa",
        gymName: "주안 우피짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/182901735e51979a9e/4K8gHiDpW86ASgDNVCchRM8YRLuXU15tyWXQLj6Yxkit.jpg",
        address: "인천 미추홀구 주안동",
        location: [126.68007142817409, 37.45256693821056],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "주차 시간제한 없음",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 474050,
          originalPrice: 499000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 6,
        },
        review: {
          rate: 4.95,
          count: 21,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "63be77d732bae8001dcfbf64",
        gymName: "주안 프레임짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/185a00420111ca00de/4K8gvPhz1FqN9veZ5Af7UfX19N95uc69b5qrDnARk99i.jpg",
        address: "인천 미추홀구 주안동",
        location: [126.68113655750123, 37.457906044342884],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["P.T", "헬스"],
        program: {
          free: "‍ OT",
        },
        service: {
          free: "️ 주차 2시간 가능 / 샤워실 / 수건 / 인바디",
        },
        price: {
          name: "1:1 P.T",
          count: null,
          isLowestPrice: true,
          lowestPrice: 4700000,
          originalPrice: 4750000,
          period: 12,
          priceType: "period",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: 10,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6268da149666fb001debc626",
        gymName: "송도 5150피트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1806993e1e65a77688/4K8ftLJhS8JYuzqJ1RTUBBM83eVnBqi8HBpEZEgtnw4L.jpg",
        address: "인천 연수구 송도동",
        location: [126.65206948082276, 37.39497388053794],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "O.T 월 3회 (신청자에 한하여 운영, 트레이너와 스케줄 조율 필요)",
        },
        service: {
          free: "수건 / 샤워시설 / 주차2시간 / WI-FI",
        },
        price: {
          name: "헬스",
          count: null,
          isLowestPrice: false,
          lowestPrice: 480000,
          originalPrice: 480000,
          period: 12,
          priceType: "period",
          itemTags: [],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.75,
          count: 4,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6049b4c343115b00392223c8",
        gymName: "주안 바디제이짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1781fea1ada5b1ee10/4K7pBx166EagmHmJq9wrAuRiq1LCYNjrAjSqJ1qkGt3A.jpg",
        address: "인천 미추홀구 주안동",
        location: [126.68471893348678, 37.458437583686504],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️수건 / Wi-fi",
        },
        price: {
          name: "헬스",
          count: null,
          isLowestPrice: false,
          lowestPrice: 480000,
          originalPrice: 480000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 1,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "638ff3d50e1e84001dd22ca8",
        gymName: "송도 리조트휘트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/184ea507bc71196185/4K8gixguYnxL5UZqQvCsCHFjiPLmedA72QYkjHLbiD5r.jpg",
        address: "인천 연수구 송도동",
        location: [126.65011055127258, 37.39488250365813],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "주차 3시간 가능",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 528000,
          originalPrice: 528000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 2,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6406ff7832519b001de7f203",
        gymName: "주안 웨이빗 피트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/186bb55efad4519160/gWt1zjjXv6Pni3wbRz5EVkdVurvt3YTJLt.센터 Small 복사.jpg",
        address: "인천 미추홀구 주안동",
        location: [126.68053448581358, 37.46127644308608],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "헬스 등록시 PT2회 sv / ‍️그룹 PT월 2회 sv / 개인 샤워실 / 샴푸,바디워시 / 수건 / ️ 수전 / 제빙기 / 공용 락커 / 인바디 / ️ 주차 3시간 가능",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 726000,
          originalPrice: 840000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 8,
        },
        review: {
          rate: 4.95,
          count: 39,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
    ],
  },
};
